In [ ]:
import pandas as pd
import os
url = r"C:\Users\Lenovo\OneDrive\Desktop\Cleaning_practise\sample_sales_data_messy.xlsx"
Sales_table = pd.read_excel(url)
print(Sales_table.head(10))

   Order ID  Order Date        Product Name     Category Region     Sales Rep  \
0    1000.0  2024-08-04        Office Chair    Furniture   West    Priya Nair
1    1001.0  2024-05-22        Notebook Set   Stationery   West  Carlos Diaz
2    1002.0  02-07-2024       Standing Desk    Furniture   West     Wei Zhang
3    1003.0  04/07/2024      wireless mouse  electronics  South  Carlos Diaz
4    1004.0  21-11-2024   Bluetooth Speaker  Electronics  South   Priya  Nair
5    1005.0  18/05/2024      Filing Cabinet    Furniture   East  Carlos Diaz
6    1006.0  27/04/2025  Ergonomic Keyboard  Electronics  SOUTH  Amara Okafor
7    1007.0  14/10/2024  Ergonomic Keyboard  Electronics  West     Priya Nair
8    1008.0  2025-01-21       Monitor Stand  Electronics  SOUTH   Priya  Nair
9    1009.0  27-09-2024       office  chair   furniture   South  Amara Okafor

  Quantity  Unit Price  Total Sales Payment Method          Customer Email
0        1      372.07       372.07    credit card        priya.nair@email
1        5     $255.15      1275.75           Cash   carlos.diaz@EMAIL.com
2        0      173.42          NaN    credit card     wei.zhang@email.com
3      NaN      270.43          NaN  Bank Transfer       carlos.diaz@email
4        1  USD 332.33       332.33    credit card                     NaN
5        5     $336.74      1683.70         paypal   carlos.diaz@EMAIL.com
6        1     $118.38       118.38  Bank Transfer  amara.okafor@email.com
7        5      329.44      1647.20  Bank Transfer    priya.nair@EMAIL.com
8        0      449.42          NaN         PayPal       priya..nair@email
9        3      397.08      1191.24           Cash      amara.okafor@email

In [662]:
print(Sales_table.shape)
print(Sales_table.info())
print(Sales_table.describe())

(256, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    float64
 1   Order Date      254 non-null    object
 2   Product Name    254 non-null    object
 3   Category        254 non-null    object
 4   Region          254 non-null    object
 5   Sales Rep       233 non-null    object
 6   Quantity        224 non-null    object
 7   Unit Price      254 non-null    object
 8   Total Sales     148 non-null    float64
 9   Payment Method  227 non-null    object
 10  Customer Email  153 non-null    object
dtypes: float64(2), object(9)
memory usage: 22.1+ KB
None
          Order ID  Total Sales
count   254.000000   148.000000
mean   1125.283465  1105.753649
std      72.903249  1066.037623
min    1000.000000    30.020000
25%    1062.250000   371.362500
50%    1125.500000   816.600000
75%    1188.750000  1444.897500
max    1249.000000  4729.700000

In [663]:
Sales_table = Sales_table.rename(columns={"Category":"Categories"})
Sales_table = Sales_table.rename(columns={"Region":"Regions"})
Sales_table

,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,1000.0,2024-08-04,Office Chair,Furniture,West,Priya Nair,1,372.07,372.07,credit card,priya.nair@email
1,1001.0,2024-05-22,Notebook Set,Stationery,West,Carlos Diaz,5,$255.15,1275.75,Cash,carlos.diaz@EMAIL.com
2,1002.0,02-07-2024,Standing Desk,Furniture,West,Wei Zhang,0,173.42,NaN,credit card,wei.zhang@email.com
3,1003.0,04/07/2024,wireless mouse,electronics,South,Carlos Diaz,NaN,270.43,NaN,Bank Transfer,carlos.diaz@email
4,1004.0,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1,USD 332.33,332.33,credit card,NaN
...,...,...,...,...,...,...,...,...,...,...,...
251,1245.0,"March 11, 2024",whiteboard,office supplies,South,john smith,2,$118.33,236.66,bank transfer,NaN
252,1246.0,"March 18, 2024",office chair,furniture,East,Wei Zhang,3,$38.86,116.58,bank transfer,wei..zhang@EMAIL.com
253,1247.0,06/10/2024,Whiteboard,Office Supplies,East,john smith,5,$47.91,239.55,Cash,NaN
254,1248.0,"April 06, 2024",Bluetooth Speaker,Electronics,North,Carlos Diaz,5,USD 278.93,1394.65,paypal,carlos.diaz@email
255,1249.0,07-01-2024,wireless mouse,electronics,West,Wei Zhang,5,$249.97,1249.85,credit card,wei..zhang@email

In [693]:
dup_ordID = Sales_table["Order ID"].duplicated().sum()
null_values = Sales_table[Sales_table["Order ID"].isna()]
print(dup_ordID)
null_values

0

Empty DataFrame
Columns: [index, Order ID, Order Date, Product Name, Categories, Regions, Sales Rep, Quantity, Unit Price, Total Sales, Payment Method, Customer Email]
Index: []

In [694]:
seen = set()
Sales_table = Sales_table.dropna(subset=["Order ID"]) #droping null value in order id column
for i,order in Sales_table["Order ID"].items():
    
    if order in seen: #check weather it is in seen or not
        if i<len(Sales_table):
            if order+1 == Sales_table.loc[i+1,"Order ID"]: 
                Sales_table = Sales_table.drop(index = i)
            else:
                Sales_table.loc[i,"Order ID"] = order+1
   
    else:
        seen.add(order)
print("Successfully cleaned")

Successfully cleaned

In [695]:
Sales_table = Sales_table.reset_index(drop=True)
Sales_table

,index,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,0,1000,04-08-2024,Office Chair,Furniture,West,Priya Nair,1.0,372.07,372.07,Credit Card,priya.nair@email.com
1,1,1001,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5.0,255.15,1275.75,Cash,carlos.diaz@email.com
2,2,1002,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1.0,332.33,332.33,Credit Card,priya.nair@email.com
3,3,1003,18-05-2024,Filing Cabinet,Furniture,East,Carlos Diaz,5.0,336.74,1683.70,Paypal,carlos.diaz@email.com
4,4,1004,27-04-2025,Ergonomic Keyboard,Electronics,South,Amara Okafor,1.0,118.38,118.38,Bank Transfer,amara.okafor@email.com
...,...,...,...,...,...,...,...,...,...,...,...,...
164,164,1164,11-03-2024,Whiteboard,Office Supplies,South,john smith,2.0,118.33,236.66,Bank Transfer,john.smith@email.com
165,165,1165,18-03-2024,Office Chair,Furniture,East,Wei Zhang,3.0,38.86,116.58,Bank Transfer,wei.zhang@email.com
166,166,1166,06-10-2024,Whiteboard,Office Supplies,East,john smith,5.0,47.91,239.55,Cash,john.smith@email.com
167,167,1167,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5.0,278.93,1394.65,Paypal,carlos.diaz@email.com
168,168,1168,07-01-2024,Wireless Mouse,Electronics,West,Wei Zhang,5.0,249.97,1249.85,Credit Card,wei.zhang@email.com

In [667]:
dup = Sales_table.duplicated().sum()
print(f"duplicate in order id is {dup}")

duplicate in order id is 0

In [668]:
def format_date(value):
    value = str(value).strip()
    formats = [
        "%Y-%m-%d",   # 2024-05-24
        "%d-%m-%Y",   # 20-05-2024
        "%d/%m/%Y",   # 20/08/2023
        "%m/%d/%Y",   # in case some are US-style
        "%Y/%m/%d",
        "%B %d, %Y"
    ]
    for fmt in formats:
        try:
            return pd.to_datetime(value, format=fmt)
        except ValueError:
            continue
    return pd.NaT  # if nothing matches

Sales_table["Order Date"] = Sales_table["Order Date"].apply(format_date)

# Now format all into ONE consistent style
Sales_table["Order Date"] = Sales_table["Order Date"].dt.strftime("%d-%m-%Y")

print(Sales_table["Order Date"])

0      04-08-2024
1      22-05-2024
2      02-07-2024
3      04-07-2024
4      21-11-2024
          ...
244    11-03-2024
245    18-03-2024
246    06-10-2024
247    06-04-2024
248    07-01-2024
Name: Order Date, Length: 249, dtype: object

In [ ]:
null_dates = Sales_table["Order Date"].isnull().sum()
print(null_dates)

0

In [670]:
Sales_table["Categories"] = Sales_table["Categories"].str.strip().replace({
    "Stationery": "Stationary", "furniture": "Furniture",
    "electronics": "Electronics", "office supplies": "Office Supplies"
})

Sales_table

,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,1000.0,04-08-2024,Office Chair,Furniture,West,Priya Nair,1,372.07,372.07,credit card,priya.nair@email
1,1001.0,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5,$255.15,1275.75,Cash,carlos.diaz@EMAIL.com
2,1002.0,02-07-2024,Standing Desk,Furniture,West,Wei Zhang,0,173.42,NaN,credit card,wei.zhang@email.com
3,1003.0,04-07-2024,wireless mouse,Electronics,South,Carlos Diaz,NaN,270.43,NaN,Bank Transfer,carlos.diaz@email
4,1004.0,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1,USD 332.33,332.33,credit card,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244,1245.0,11-03-2024,whiteboard,Office Supplies,South,john smith,2,$118.33,236.66,bank transfer,NaN
245,1246.0,18-03-2024,office chair,Furniture,East,Wei Zhang,3,$38.86,116.58,bank transfer,wei..zhang@EMAIL.com
246,1247.0,06-10-2024,Whiteboard,Office Supplies,East,john smith,5,$47.91,239.55,Cash,NaN
247,1248.0,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5,USD 278.93,1394.65,paypal,carlos.diaz@email
248,1249.0,07-01-2024,wireless mouse,Electronics,West,Wei Zhang,5,$249.97,1249.85,credit card,wei..zhang@email

In [ ]:
uni_items = Sales_table["Product Name"].unique()
print(uni_items)

['Office Chair' 'Notebook Set' 'Standing Desk' 'wireless mouse'
 'Bluetooth Speaker' 'Filing Cabinet' 'Ergonomic Keyboard' 'Monitor Stand'
 'office  chair' 'Wireless Mouse' 'Desk Organizer' 'whiteboard'
 'Water Bottle' 'Coffee Mug' 'LED Desk Lamp' 'USB-C Hub' 'Whiteboard'
 'Notebook  Set' 'Sticky Notes' 'Ballpoint Pens']

In [ ]:
Sales_table["Product Name"] = Sales_table["Product Name"].str.title().replace("  "," ",regex=True)
uni_items = Sales_table["Product Name"].unique()
print(uni_items)

['Office Chair' 'Notebook Set' 'Standing Desk' 'Wireless Mouse'
 'Bluetooth Speaker' 'Filing Cabinet' 'Ergonomic Keyboard' 'Monitor Stand'
 'Desk Organizer' 'Whiteboard' 'Water Bottle' 'Coffee Mug' 'Led Desk Lamp'
 'Usb-C Hub' 'Sticky Notes' 'Ballpoint Pens']

In [ ]:
Sales_table["Regions"] = Sales_table["Regions"].astype(str).str.strip()

Empty DataFrame
Columns: [Order ID, Order Date, Product Name, Categories, Regions, Sales Rep, Quantity, Unit Price, Total Sales, Payment Method, Customer Email]
Index: []

In [ ]:
Sales_table["Sales Rep"] = Sales_table["Sales Rep"].str.strip()

Empty DataFrame
Columns: [Order ID, Order Date, Product Name, Categories, Regions, Sales Rep, Quantity, Unit Price, Total Sales, Payment Method, Customer Email]
Index: []

In [ ]:
Sales_table["Regions"] = Sales_table["Regions"].str.capitalize()
uni_items = Sales_table["Regions"].unique()
print(uni_items)

['West' 'South' 'East' 'North']

In [ ]:
uni_items = Sales_table["Payment Method"].unique()
print(uni_items)

['credit card' 'Cash' 'Bank Transfer' 'paypal' 'PayPal' 'bank transfer'
 nan 'CASH' 'Credit Card']

In [ ]:
Sales_table["Payment Method"] = Sales_table["Payment Method"].str.title()
uni_items = Sales_table["Payment Method"].unique()
print(uni_items)

['Credit Card' 'Cash' 'Bank Transfer' 'Paypal' nan]

In [680]:
Sales_table["Quantity"] = Sales_table["Quantity"].replace("five",5)
leng = len(Sales_table["Quantity"])
for i in range(0,leng):
    if Sales_table.loc[i,"Quantity"] <= 0 or pd.isna(Sales_table.loc[i,"Quantity"]) :
        Sales_table = Sales_table.drop(index=i)
Sales_table

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11324\3572898084.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Sales_table["Quantity"] = Sales_table["Quantity"].replace("five",5)

,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,1000.0,04-08-2024,Office Chair,Furniture,West,Priya Nair,1.0,372.07,372.07,Credit Card,priya.nair@email
1,1001.0,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5.0,$255.15,1275.75,Cash,carlos.diaz@EMAIL.com
4,1004.0,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1.0,USD 332.33,332.33,Credit Card,NaN
5,1005.0,18-05-2024,Filing Cabinet,Furniture,East,Carlos Diaz,5.0,$336.74,1683.70,Paypal,carlos.diaz@EMAIL.com
6,1006.0,27-04-2025,Ergonomic Keyboard,Electronics,South,Amara Okafor,1.0,$118.38,118.38,Bank Transfer,amara.okafor@email.com
...,...,...,...,...,...,...,...,...,...,...,...
244,1245.0,11-03-2024,Whiteboard,Office Supplies,South,john smith,2.0,$118.33,236.66,Bank Transfer,NaN
245,1246.0,18-03-2024,Office Chair,Furniture,East,Wei Zhang,3.0,$38.86,116.58,Bank Transfer,wei..zhang@EMAIL.com
246,1247.0,06-10-2024,Whiteboard,Office Supplies,East,john smith,5.0,$47.91,239.55,Cash,NaN
247,1248.0,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5.0,USD 278.93,1394.65,Paypal,carlos.diaz@email
248,1249.0,07-01-2024,Wireless Mouse,Electronics,West,Wei Zhang,5.0,$249.97,1249.85,Credit Card,wei..zhang@email

In [681]:
Sales_table = Sales_table.reset_index()
Sales_table

,index,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,0,1000.0,04-08-2024,Office Chair,Furniture,West,Priya Nair,1.0,372.07,372.07,Credit Card,priya.nair@email
1,1,1001.0,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5.0,$255.15,1275.75,Cash,carlos.diaz@EMAIL.com
2,4,1004.0,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1.0,USD 332.33,332.33,Credit Card,NaN
3,5,1005.0,18-05-2024,Filing Cabinet,Furniture,East,Carlos Diaz,5.0,$336.74,1683.70,Paypal,carlos.diaz@EMAIL.com
4,6,1006.0,27-04-2025,Ergonomic Keyboard,Electronics,South,Amara Okafor,1.0,$118.38,118.38,Bank Transfer,amara.okafor@email.com
...,...,...,...,...,...,...,...,...,...,...,...,...
164,244,1245.0,11-03-2024,Whiteboard,Office Supplies,South,john smith,2.0,$118.33,236.66,Bank Transfer,NaN
165,245,1246.0,18-03-2024,Office Chair,Furniture,East,Wei Zhang,3.0,$38.86,116.58,Bank Transfer,wei..zhang@EMAIL.com
166,246,1247.0,06-10-2024,Whiteboard,Office Supplies,East,john smith,5.0,$47.91,239.55,Cash,NaN
167,247,1248.0,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5.0,USD 278.93,1394.65,Paypal,carlos.diaz@email
168,248,1249.0,07-01-2024,Wireless Mouse,Electronics,West,Wei Zhang,5.0,$249.97,1249.85,Credit Card,wei..zhang@email

In [682]:
Sales_table["Unit Price"] = Sales_table["Unit Price"].astype(str).str.replace(r"[^\d.]","",regex=True)
Sales_table["Unit Price"] = pd.to_numeric(Sales_table["Unit Price"],errors= "coerce")
Sales_table

,index,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,0,1000.0,04-08-2024,Office Chair,Furniture,West,Priya Nair,1.0,372.07,372.07,Credit Card,priya.nair@email
1,1,1001.0,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5.0,255.15,1275.75,Cash,carlos.diaz@EMAIL.com
2,4,1004.0,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1.0,332.33,332.33,Credit Card,NaN
3,5,1005.0,18-05-2024,Filing Cabinet,Furniture,East,Carlos Diaz,5.0,336.74,1683.70,Paypal,carlos.diaz@EMAIL.com
4,6,1006.0,27-04-2025,Ergonomic Keyboard,Electronics,South,Amara Okafor,1.0,118.38,118.38,Bank Transfer,amara.okafor@email.com
...,...,...,...,...,...,...,...,...,...,...,...,...
164,244,1245.0,11-03-2024,Whiteboard,Office Supplies,South,john smith,2.0,118.33,236.66,Bank Transfer,NaN
165,245,1246.0,18-03-2024,Office Chair,Furniture,East,Wei Zhang,3.0,38.86,116.58,Bank Transfer,wei..zhang@EMAIL.com
166,246,1247.0,06-10-2024,Whiteboard,Office Supplies,East,john smith,5.0,47.91,239.55,Cash,NaN
167,247,1248.0,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5.0,278.93,1394.65,Paypal,carlos.diaz@email
168,248,1249.0,07-01-2024,Wireless Mouse,Electronics,West,Wei Zhang,5.0,249.97,1249.85,Credit Card,wei..zhang@email

In [683]:
null_value = Sales_table.isna().sum()
print(null_value)

index              0
Order ID           0
Order Date         0
Product Name       0
Categories         0
Regions            0
Sales Rep         17
Quantity           0
Unit Price         0
Total Sales       25
Payment Method    19
Customer Email    69
dtype: int64

In [684]:
Sales_table["Sales Rep"] = Sales_table["Sales Rep"].fillna("Guest")

In [685]:
Sales_table["Total Sales"] = Sales_table["Total Sales"].fillna(Sales_table["Quantity"]*Sales_table["Unit Price"])

In [686]:
Sales_table["Payment Method"] = Sales_table["Payment Method"].fillna("Unknow")

In [687]:
Sales_table["Sales Rep"] = Sales_table["Sales Rep"].str.replace("  "," ",regex=True) #removed double spaces from Salesrep column

In [688]:
Sales_table["Customer Email"] = Sales_table["Sales Rep"].str.lower().replace(" ",".",regex=True) + "@email.com"
Sales_table

,index,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,0,1000.0,04-08-2024,Office Chair,Furniture,West,Priya Nair,1.0,372.07,372.07,Credit Card,priya.nair@email.com
1,1,1001.0,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5.0,255.15,1275.75,Cash,carlos.diaz@email.com
2,4,1004.0,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1.0,332.33,332.33,Credit Card,priya.nair@email.com
3,5,1005.0,18-05-2024,Filing Cabinet,Furniture,East,Carlos Diaz,5.0,336.74,1683.70,Paypal,carlos.diaz@email.com
4,6,1006.0,27-04-2025,Ergonomic Keyboard,Electronics,South,Amara Okafor,1.0,118.38,118.38,Bank Transfer,amara.okafor@email.com
...,...,...,...,...,...,...,...,...,...,...,...,...
164,244,1245.0,11-03-2024,Whiteboard,Office Supplies,South,john smith,2.0,118.33,236.66,Bank Transfer,john.smith@email.com
165,245,1246.0,18-03-2024,Office Chair,Furniture,East,Wei Zhang,3.0,38.86,116.58,Bank Transfer,wei.zhang@email.com
166,246,1247.0,06-10-2024,Whiteboard,Office Supplies,East,john smith,5.0,47.91,239.55,Cash,john.smith@email.com
167,247,1248.0,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5.0,278.93,1394.65,Paypal,carlos.diaz@email.com
168,248,1249.0,07-01-2024,Wireless Mouse,Electronics,West,Wei Zhang,5.0,249.97,1249.85,Credit Card,wei.zhang@email.com

In [689]:
#rearraning index values
Sales_table["index"] = range(0,len(Sales_table))
Sales_table

,index,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,0,1000.0,04-08-2024,Office Chair,Furniture,West,Priya Nair,1.0,372.07,372.07,Credit Card,priya.nair@email.com
1,1,1001.0,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5.0,255.15,1275.75,Cash,carlos.diaz@email.com
2,2,1004.0,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1.0,332.33,332.33,Credit Card,priya.nair@email.com
3,3,1005.0,18-05-2024,Filing Cabinet,Furniture,East,Carlos Diaz,5.0,336.74,1683.70,Paypal,carlos.diaz@email.com
4,4,1006.0,27-04-2025,Ergonomic Keyboard,Electronics,South,Amara Okafor,1.0,118.38,118.38,Bank Transfer,amara.okafor@email.com
...,...,...,...,...,...,...,...,...,...,...,...,...
164,164,1245.0,11-03-2024,Whiteboard,Office Supplies,South,john smith,2.0,118.33,236.66,Bank Transfer,john.smith@email.com
165,165,1246.0,18-03-2024,Office Chair,Furniture,East,Wei Zhang,3.0,38.86,116.58,Bank Transfer,wei.zhang@email.com
166,166,1247.0,06-10-2024,Whiteboard,Office Supplies,East,john smith,5.0,47.91,239.55,Cash,john.smith@email.com
167,167,1248.0,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5.0,278.93,1394.65,Paypal,carlos.diaz@email.com
168,168,1249.0,07-01-2024,Wireless Mouse,Electronics,West,Wei Zhang,5.0,249.97,1249.85,Credit Card,wei.zhang@email.com

In [690]:
ini_v = int(Sales_table.loc[0,"Order ID"])
print(type(ini_v))
Sales_table["Order ID"] = range(ini_v,ini_v+len(Sales_table))
Sales_table

<class 'int'>

,index,Order ID,Order Date,Product Name,Categories,Regions,Sales Rep,Quantity,Unit Price,Total Sales,Payment Method,Customer Email
0,0,1000,04-08-2024,Office Chair,Furniture,West,Priya Nair,1.0,372.07,372.07,Credit Card,priya.nair@email.com
1,1,1001,22-05-2024,Notebook Set,Stationary,West,Carlos Diaz,5.0,255.15,1275.75,Cash,carlos.diaz@email.com
2,2,1002,21-11-2024,Bluetooth Speaker,Electronics,South,Priya Nair,1.0,332.33,332.33,Credit Card,priya.nair@email.com
3,3,1003,18-05-2024,Filing Cabinet,Furniture,East,Carlos Diaz,5.0,336.74,1683.70,Paypal,carlos.diaz@email.com
4,4,1004,27-04-2025,Ergonomic Keyboard,Electronics,South,Amara Okafor,1.0,118.38,118.38,Bank Transfer,amara.okafor@email.com
...,...,...,...,...,...,...,...,...,...,...,...,...
164,164,1164,11-03-2024,Whiteboard,Office Supplies,South,john smith,2.0,118.33,236.66,Bank Transfer,john.smith@email.com
165,165,1165,18-03-2024,Office Chair,Furniture,East,Wei Zhang,3.0,38.86,116.58,Bank Transfer,wei.zhang@email.com
166,166,1166,06-10-2024,Whiteboard,Office Supplies,East,john smith,5.0,47.91,239.55,Cash,john.smith@email.com
167,167,1167,06-04-2024,Bluetooth Speaker,Electronics,North,Carlos Diaz,5.0,278.93,1394.65,Paypal,carlos.diaz@email.com
168,168,1168,07-01-2024,Wireless Mouse,Electronics,West,Wei Zhang,5.0,249.97,1249.85,Credit Card,wei.zhang@email.com

In [ ]:
print(Sales_table.shape)
print(Sales_table.info())
print(Sales_table.describe())

(169, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           169 non-null    int64
 1   Order ID        169 non-null    int64
 2   Order Date      169 non-null    object
 3   Product Name    169 non-null    object
 4   Categories      169 non-null    object
 5   Regions         169 non-null    object
 6   Sales Rep       169 non-null    object
 7   Quantity        169 non-null    float64
 8   Unit Price      169 non-null    float64
 9   Total Sales     169 non-null    float64
 10  Payment Method  169 non-null    object
 11  Customer Email  169 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 16.0+ KB
None
            index     Order ID    Quantity  Unit Price  Total Sales
count  169.000000   169.000000  169.000000  169.000000   169.000000
mean    84.000000  1084.000000    4.426036  253.457337  1120.491065
std     48.930222    48.930222    2.863279  138.581246  1001.034872
min      0.000000  1000.000000    1.000000   12.360000    30.020000
25%     42.000000  1042.000000    2.000000  128.080000   396.600000
50%     84.000000  1084.000000    5.000000  261.750000   825.030000
75%    126.000000  1126.000000    5.000000  368.230000  1482.800000
max    168.000000  1168.000000   10.000000  499.790000  4729.700000